// This file was automatically generated by genny.
// Any changes will be lost if this file is regenerated.
// see https://github.com/cheekybits/genny

package array

// TSum T数组求和
func Float32Sum(arr []float32) (v float32) {
	for _, i := range arr {
		v += i
	}
	return v
}

// TSum T数组求和
func Float64Sum(arr []float64) (v float64) {
	for _, i := range arr {
		v += i
	}
	return v
}

// TSum T数组求和
func IntSum(arr []int) (v int) {
	for _, i := range arr {
		v += i
	}
	return v
}

// TSum T数组求和
func Int16Sum(arr []int16) (v int16) {
	for _, i := range arr {
		v += i
	}
	return v
}

// TSum T数组求和
func Int32Sum(arr []int32) (v int32) {
	for _, i := range arr {
		v += i
	}
	return v
}

// TSum T数组求和
func Int64Sum(arr []int64) (v int64) {
	for _, i := range arr {
		v += i
	}
	return v
}

// TSum T数组求和
func Int8Sum(arr []int8) (v int8) {
	for _, i := range arr {
		v += i
	}
	return v
}

// TSum T数组求和
func UintSum(arr []uint) (v uint) {
	for _, i := range arr {
		v += i
	}
	return v
}

// TSum T数组求和
func Uint16Sum(arr []uint16) (v uint16) {
	for _, i := range arr {
		v += i
	}
	return v
}

// TSum T数组求和
func Uint32Sum(arr []uint32) (v uint32) {
	for _, i := range arr {
		v += i
	}
	return v
}

// TSum T数组求和
func Uint64Sum(arr []uint64) (v uint64) {
	for _, i := range arr {
		v += i
	}
	return v
}

// TSum T数组求和
func Uint8Sum(arr []uint8) (v uint8) {
	for _, i := range arr {
		v += i
	}
	return v
}
