// This file was automatically generated by genny.
// Any changes will be lost if this file is regenerated.
// see https://github.com/cheekybits/genny

package array

// Float32In 搜索数组中是否存在指定的值。
// @param search float32 要索索的值
// @param slice []Float32 要搜索的数组
// @return  bool 是否存在
// @date 2021-03-15 03:35:25
func Float32In(search float32, slice []float32) bool {
	for _, v := range slice {
		if v == search {
			return true
		}
	}
	return false
}

// Float64In 搜索数组中是否存在指定的值。
// @param search float64 要索索的值
// @param slice []Float64 要搜索的数组
// @return  bool 是否存在
// @date 2021-03-15 03:35:25
func Float64In(search float64, slice []float64) bool {
	for _, v := range slice {
		if v == search {
			return true
		}
	}
	return false
}

// IntIn 搜索数组中是否存在指定的值。
// @param search int 要索索的值
// @param slice []Int 要搜索的数组
// @return  bool 是否存在
// @date 2021-03-15 03:35:25
func IntIn(search int, slice []int) bool {
	for _, v := range slice {
		if v == search {
			return true
		}
	}
	return false
}

// Int16In 搜索数组中是否存在指定的值。
// @param search int16 要索索的值
// @param slice []Int16 要搜索的数组
// @return  bool 是否存在
// @date 2021-03-15 03:35:25
func Int16In(search int16, slice []int16) bool {
	for _, v := range slice {
		if v == search {
			return true
		}
	}
	return false
}

// Int32In 搜索数组中是否存在指定的值。
// @param search int32 要索索的值
// @param slice []Int32 要搜索的数组
// @return  bool 是否存在
// @date 2021-03-15 03:35:25
func Int32In(search int32, slice []int32) bool {
	for _, v := range slice {
		if v == search {
			return true
		}
	}
	return false
}

// Int64In 搜索数组中是否存在指定的值。
// @param search int64 要索索的值
// @param slice []Int64 要搜索的数组
// @return  bool 是否存在
// @date 2021-03-15 03:35:25
func Int64In(search int64, slice []int64) bool {
	for _, v := range slice {
		if v == search {
			return true
		}
	}
	return false
}

// Int8In 搜索数组中是否存在指定的值。
// @param search int8 要索索的值
// @param slice []Int8 要搜索的数组
// @return  bool 是否存在
// @date 2021-03-15 03:35:25
func Int8In(search int8, slice []int8) bool {
	for _, v := range slice {
		if v == search {
			return true
		}
	}
	return false
}

// UintIn 搜索数组中是否存在指定的值。
// @param search uint 要索索的值
// @param slice []Uint 要搜索的数组
// @return  bool 是否存在
// @date 2021-03-15 03:35:25
func UintIn(search uint, slice []uint) bool {
	for _, v := range slice {
		if v == search {
			return true
		}
	}
	return false
}

// Uint16In 搜索数组中是否存在指定的值。
// @param search uint16 要索索的值
// @param slice []Uint16 要搜索的数组
// @return  bool 是否存在
// @date 2021-03-15 03:35:25
func Uint16In(search uint16, slice []uint16) bool {
	for _, v := range slice {
		if v == search {
			return true
		}
	}
	return false
}

// Uint32In 搜索数组中是否存在指定的值。
// @param search uint32 要索索的值
// @param slice []Uint32 要搜索的数组
// @return  bool 是否存在
// @date 2021-03-15 03:35:25
func Uint32In(search uint32, slice []uint32) bool {
	for _, v := range slice {
		if v == search {
			return true
		}
	}
	return false
}

// Uint64In 搜索数组中是否存在指定的值。
// @param search uint64 要索索的值
// @param slice []Uint64 要搜索的数组
// @return  bool 是否存在
// @date 2021-03-15 03:35:25
func Uint64In(search uint64, slice []uint64) bool {
	for _, v := range slice {
		if v == search {
			return true
		}
	}
	return false
}

// Uint8In 搜索数组中是否存在指定的值。
// @param search uint8 要索索的值
// @param slice []Uint8 要搜索的数组
// @return  bool 是否存在
// @date 2021-03-15 03:35:25
func Uint8In(search uint8, slice []uint8) bool {
	for _, v := range slice {
		if v == search {
			return true
		}
	}
	return false
}

// StringIn 搜索数组中是否存在指定的值。
// @param search string 要索索的值
// @param slice []String 要搜索的数组
// @return  bool 是否存在
// @date 2021-03-15 03:35:25
func StringIn(search string, slice []string) bool {
	for _, v := range slice {
		if v == search {
			return true
		}
	}
	return false
}
