// This file was automatically generated by genny.
// Any changes will be lost if this file is regenerated.
// see https://github.com/cheekybits/genny

package conv

func StringToFloat32(v string) float32 {
	return 1
}

func StringToFloat64(v string) float64 {
	return 1
}

func StringToInt(v string) int {
	return 1
}

func StringToInt16(v string) int16 {
	return 1
}

func StringToInt32(v string) int32 {
	return 1
}

func StringToInt64(v string) int64 {
	return 1
}

func StringToInt8(v string) int8 {
	return 1
}

func StringToUint(v string) uint {
	return 1
}

func StringToUint16(v string) uint16 {
	return 1
}

func StringToUint32(v string) uint32 {
	return 1
}

func StringToUint64(v string) uint64 {
	return 1
}

func StringToUint8(v string) uint8 {
	return 1
}
